export const majorPageConstants = {
    jobAm: "Աշխատանք",
    serviceAm: "Ծառայություններ",
    realEstateAm: "Անշարժ գույք",
    transportAm: "Տրանսպորտ",
    elektronicsAm: "Էլեկտրոնիկա",
    fashionAm: "Նորաձևություն եւ ոճ",
    homeGardenAm: "Տուն և այգի",
    houseHoldAppliancesAm: "Կենցաղային տեխնիկա",
    equipmentAm: "Սարքավորումներ և նյութեր",
    offerAm: "Առաջարկում եմ",
    lookingForAm: "Փնտրում եմ",
    withPhotoAm: "Լուսանկարով",
    regionAm: "Տարածաշրջան",
    jobRu: "Работа",
    serviceRu: "Услуги",
    realEstateRu: "Недвижимость",
    transportRu: "Транспорт",
    elektronicsRu: "Электроника",
    fashionRu: "Мода и стиль",
    homeGardenRu: "Дом и сад",
    houseHoldAppliancesRu: "Бытовая техника",
    equipmentRu: "Оборудование и материалы",
    offerRu: "Предлагаю",
    lookingForRu: "Ищу",
    withPhotoRu: "Объявления с фото",
    regionRu: "Регион",
    jobEn: "Jobs",
    serviceEn: "Services",
    realEstateEn: "Real Estate",
    transportEn: "Vehicles",
    elektronicsEn: "Electronics",
    fashionEn: "Clothing and Fashion",
    homeGardenEn: "Home and Garden",
    houseHoldAppliancesEn: "Appliances",
    equipmentEn: "Equipment and Materials",
    offerEn: "Offered",
    lookingForEn: "Wanted",
    withPhotoEn: "Ads with photos",
    regionEn: "Location",
    

}
export const resultsPageConstants = {
    offer: "Առաջարկում եմ",
    lookingFor: "Փնտրում եմ",
    withPhoto: "Լուսանկարով",
    region: "Տարածաշրջան",
    norNorq: "Նոր Նորք",
    price: "Գին"
}